site :opscode

cookbook 'vnc'
cookbook 'chef-client'
cookbook 'apt'
cookbook 'monit'
cookbook 'postfix'
cookbook 'openssh'
cookbook 'ntp'
cookbook 'vim'
cookbook 'build-essential'
cookbook 'user'
cookbook 'logrotate'
cookbook 'ohai'
cookbook 'ruby_build'
cookbook 'rvm'
cookbook 'sudo'
cookbook 'zsh'
cookbook 'oh-my-zsh'
cookbook 'collectd'
cookbook 'htop'
cookbook 'runit'
cookbook 'rsyslog'

cookbook 'imagemagick'
cookbook 'nginx'
cookbook 'unicorn'
